kind: pipeline
type: docker
name: unit tests

steps:
  - name: go vet and unit tests
    image: golang:1.17
    commands:
      - go vet ./...
      - go test -cover ./...
    volumes:
      - name: cache
        path: /go
    depends_on:
      - clone
  - name: golangci-lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --timeout 300s
    volumes:
      - name: cache
        path: /go
    depends_on:
      - clone

volumes:
  - name: cache
    temp: {}

---
kind: pipeline
type: aws
name: ubuntu acceptance tests

pool:
  use: ubuntu

steps:
  - name: build
    image: golang:1.17
    commands:
      - go build
      - ls -al
  - name: server
    detach: true
    commands:
      - ls -al
      - touch .env
      - ./lite-engine certs
      - ls -al /tmp/certs
      - ./lite-engine server 
    depends_on:
      - build
  - name: run certs client
    commands:
      - sleep 5
      - ls -al
      - ./lite-engine client
    depends_on:
      - server
